'use client';

import { useEffect, useRef } from 'react';
import styles from './SoftNeuralField.module.css';

export default function SoftNeuralField({
  particleCount = 50,
    fps = 24,
    }: {
      particleCount?: number;
        fps?: number;
        }) {
          const canvasRef = useRef<HTMLCanvasElement>(null);
            const particles = useRef<Array<{
                x: number;
                    y: number;
                        vx: number;
                            vy: number;
                                size: number;
                                    hue: number;
                                        life: number;
                                          }>>([]);

                                            // Inicializa partículas
                                              const init = () => {
                                                  const canvas = canvasRef.current;
                                                      if (!canvas) return;

                                                          const w = canvas.width;
                                                              const h = canvas.height;
                                                                  particles.current = Array.from({ length: particleCount }, () => ({
                                                                        x: Math.random() * w,
                                                                              y: Math.random() * h,
                                                                                    vx: (Math.random() - 0.5) * 1.0,
                                                                                          vy: (Math.random() - 0.5) * 1.0,
                                                                                                size: 1 + Math.random() * 2,
                                                                                                      hue: 180 + Math.random() * 40,
                                                                                                            life: 1,
                                                                                                                }));
                                                                                                                  };

                                                                                                                    // Atualiza partículas
                                                                                                                      const update = () => {
                                                                                                                          const canvas = canvasRef.current;
                                                                                                                              if (!canvas) return;

                                                                                                                                  const w = canvas.width;
                                                                                                                                      const h = canvas.height;

                                                                                                                                          for (const p of particles.current) {      // Movimento suave
                                                                                                                                                p.x += p.vx;
                                                                                                                                                      p.y += p.vy;

                                                                                                                                                            // Leve turbulência
                                                                                                                                                                  p.vx += (Math.random() - 0.5) * 0.02;
                                                                                                                                                                        p.vy += (Math.random() - 0.5) * 0.02;

                                                                                                                                                                              // Limita velocidade
                                                                                                                                                                                    const speed = Math.hypot(p.vx, p.vy);
                                                                                                                                                                                          if (speed > 1.2) {
                                                                                                                                                                                                  p.vx = (p.vx / speed) * 1.2;
                                                                                                                                                                                                          p.vy = (p.vy / speed) * 1.2;
                                                                                                                                                                                                                }

                                                                                                                                                                                                                      // Reaparece nas bordas
                                                                                                                                                                                                                            if (p.x < -10) p.x = w + 10;
                                                                                                                                                                                                                                  if (p.x > w + 10) p.x = -10;
                                                                                                                                                                                                                                        if (p.y < -10) p.y = h + 10;
                                                                                                                                                                                                                                              if (p.y > h + 10) p.y = -10;

                                                                                                                                                                                                                                                    // Renova partícula
                                                                                                                                                                                                                                                          p.life -= 0.001;
                                                                                                                                                                                                                                                                if (p.life <= 0) {
                                                                                                                                                                                                                                                                        p.x = Math.random() * w;
                                                                                                                                                                                                                                                                                p.y = Math.random() * h;
                                                                                                                                                                                                                                                                                        p.life = 1;
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                      // Renderiza partículas
                                                                                                                                                                                                                                                                                                        const render = () => {
                                                                                                                                                                                                                                                                                                            const canvas = canvasRef.current;
                                                                                                                                                                                                                                                                                                                const ctx = canvas?.getContext('2d');
                                                                                                                                                                                                                                                                                                                    if (!ctx || !canvas) return;

                                                                                                                                                                                                                                                                                                                        // Limpa com transparência para manter fundo CSS visível
                                                                                                                                                                                                                                                                                                                            ctx.clearRect(0, 0, canvas.width, canvas.height);

                                                                                                                                                                                                                                                                                                                                // Desenha partículas
                                                                                                                                                                                                                                                                                                                                    for (const p of particles.current) {
                                                                                                                                                                                                                                                                                                                                          const alpha = 0.3 * p.life;
                                                                                                                                                                                                                                                                                                                                                if (alpha <= 0) continue;

                                                                                                                                                                                                                                                                                                                                                      ctx.save();
                                                                                                                                                                                                                                                                                                                                                            ctx.globalAlpha = alpha;
                                                                                                                                                                                                                                                                                                                                                                  ctx.fillStyle = `hsl(${p.hue}, 70%, 65%)`;
                                                                                                                                                                                                                                                                                                                                                                        ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                              ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);      ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                    ctx.restore();
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                            // Loop animado
                                                                                                                                                                                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                  const canvas = canvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                      if (!canvas) return;

                                                                                                                                                                                                                                                                                                                                                                                                          // Ajusta tamanho
                                                                                                                                                                                                                                                                                                                                                                                                              const resize = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.width = window.innerWidth;
                                                                                                                                                                                                                                                                                                                                                                                                                          canvas.height = window.innerHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                  resize();
                                                                                                                                                                                                                                                                                                                                                                                                                                      window.addEventListener('resize', resize);

                                                                                                                                                                                                                                                                                                                                                                                                                                          // Inicia
                                                                                                                                                                                                                                                                                                                                                                                                                                              init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                  let lastTime = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const interval = 1000 / fps;

                                                                                                                                                                                                                                                                                                                                                                                                                                                          const animate = (time: number) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (time - lastTime >= interval) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lastTime = time;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                update();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    requestAnimationFrame(animate);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            requestAnimationFrame(animate);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return () => window.removeEventListener('resize', resize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, [particleCount, fps]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`fixed inset-0 w-full h-full pointer-events-none z-0 ${styles.field}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }